remote_theme: just-the-docs/just-the-docs
title: heavendata.com
logo: "/layout/heavendata-logo.png"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/heavendata/heavendata.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"