// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import lucode from 'lucode-starlight';
import { scribanTryIt } from './src/plugins/scriban-try-it.mjs';

export default defineConfig({
  site: 'https://docs.heavendata.com',

  // Reproduces the URL scheme of the Jekyll site this replaced: a page renders at
  // /en/settings/attributes.html, not /en/settings/attributes/. 22 of the 29
  // published URLs stay byte-identical this way, including every docs URL the
  // product deep-links to. Changing this breaks customer bookmarks and the app's
  // help buttons — see pim-docs/plans/user-documentation/starlight-migration.md.
  //
  // It must be 'file', NOT 'preserve'. Both emit the same filenames here, but
  // Starlight builds its own hrefs (sidebar, prev/next, logo) from its routing
  // model: under 'preserve' it emits attributes.html while linking to
  // /attributes/, so every navigation link 404s on a site that builds green.
  build: { format: 'file' },

  // The 2026-09-02 restructure (content-structure.md) moved most pages. These
  // redirects are PERMANENT, not a migration step: bookmarks, search results and
  // — the one people forget — app builds already loaded in a user's browser keep
  // requesting the old URLs long after the app's own links are updated.
  //
  // Keys have no .html because Astro routes do not; `build.format: 'file'` emits
  // each one as <key>.html, which is what the old site served.
  //
  // The three marked (product) are linked from inside the product itself and must
  // never be removed.
  redirects: {
    '/en/initial-setup': '/en/start.html',
    '/en/initial-setup/setup-options': '/en/start/setup-options.html',
    '/en/initial-setup/first-steps': '/en/start/first-steps.html',
    '/en/initial-setup/optimize-catalog-structure': '/en/start/optimize-catalog-structure.html',

    '/en/app': '/en/products.html',
    '/en/app/product-list': '/en/products/product-list.html',

    '/en/distribution': '/en/channels.html',
    '/en/distribution/setup-custom-product-feed': '/en/channels/setup-custom-product-feed.html',
    '/en/distribution/templates': '/en/channels/templates.html', // (product) channel template editor
    '/en/distribution/ftp-pull': '/en/import/ftp-pull.html',

    // "Settings" is gone as a section: its pages belong to five different jobs
    // and moved to the section that owns each. The old index goes to Concepts,
    // where most of them landed.
    '/en/settings': '/en/concepts.html',
    '/en/settings/attributes': '/en/concepts/attributes.html',
    '/en/settings/attribute-roles': '/en/concepts/attribute-roles.html',
    '/en/settings/product-types': '/en/concepts/product-types.html',
    '/en/settings/common-attributes': '/en/concepts/common-attributes.html',
    '/en/settings/product-variants': '/en/concepts/product-variants.html',
    '/en/settings/custom-entities': '/en/concepts/custom-entities.html',
    '/en/settings/languages': '/en/concepts/languages.html',
    '/en/settings/asset-variants': '/en/assets/asset-variants.html',
    '/en/settings/brand-portal': '/en/brand-portal/overview.html',
    '/en/settings/background-jobs': '/en/troubleshooting/background-jobs.html',
  },

  integrations: [
    starlight({
      title: 'heavendata.com',
      description: 'heavendata Product Data Platform — user documentation',
      // The wordmark sets "heaven" in the brand navy rgb(16,16,58), which is
      // invisible on a dark background — only "data" stayed readable. The dark
      // variant recolours that half to white and is generated from the light one
      // by `node scripts/make-logo-assets.mjs`; regenerate it if the logo changes.
      logo: {
        light: './src/assets/heavendata-logo.png',
        dark: './src/assets/heavendata-logo-dark.png',
        alt: 'heavendata.com',
        replacesTitle: true,
      },
      // The hexagon icon cropped out of the wordmark — a 4.66:1 wordmark is
      // illegible at 16x16. Generated by scripts/make-logo-assets.mjs.
      favicon: '/favicon.png',
      customCss: ['./src/styles/custom.css'],
      // Appends the "may be out of date" notice to pages with `reviewed: false`.
      // One place, so the copy and the rule live together — see the component.
      components: { PageTitle: './src/components/PageTitle.astro' },
      plugins: [lucode()],
      // A generated "Try it" link under Scriban fences marked `try` — see the plugin.
      expressiveCode: { plugins: [scribanTryIt()] },


      // `locales` is deliberately NOT configured yet, even though the content
      // already lives under src/content/docs/en/ and publishes at /en/… .
      //
      // Turning it on makes Starlight's chrome locale-aware, and the logo then
      // links to the locale root /en.html — which does not exist, because the
      // Jekyll site never had an /en/ landing page either (it 404s there today).
      // The result is a broken header link on every page. Authoring that landing
      // page is an information-architecture decision, and IA belongs to the
      // content project, not to this 1:1 migration.
      //
      // Enabling i18n later is: add `defaultLocale`/`locales`, create
      // en/index.md, and change the autogenerate directories below to drop the
      // `en/` prefix (they become relative to the locale root).

      editLink: { baseUrl: 'https://github.com/heavendata/heavendata.github.io/edit/main/' },

      // `lastUpdated` is deliberately OFF. It reads git history, and this
      // migration rewrites every content path — so every page would advertise
      // itself as updated today when most of it is from 2021. Turn it on once the
      // content project has actually been through the pages.

      // NOTE: autogenerate directories are relative to src/content/docs, so they
      // carry the `en/` prefix while `locales` is off. If locales are ever turned
      // on, they become relative to the locale root and the prefix must go.
      // Getting this wrong yields an empty sidebar with no error and no warning.
      // The eleven sections of pim-docs/plans/user-documentation/content-structure.md.
      // Section 8 (Customers & orders) is deliberately absent: it is behind a
      // feature flag and unpublished until GA (decision D-G).
      sidebar: [
        { label: 'Start here', items: [{ autogenerate: { directory: 'en/start' } }] },
        { label: 'Concepts', items: [{ autogenerate: { directory: 'en/concepts' } }] },
        { label: 'Products', items: [{ autogenerate: { directory: 'en/products' } }] },
        { label: 'Assets & media', items: [{ autogenerate: { directory: 'en/assets' } }] },
        { label: 'Importing data', items: [{ autogenerate: { directory: 'en/import' } }] },
        // Channels is configured by hand rather than autogenerated, because it has
        // sub-groups and autogenerate labels a group with its raw directory name
        // ("templates"). Starlight offers no way to rename a generated group.
        //
        // Sub-groups matter for more than tidiness: the theme renders a TOP-LEVEL
        // group as an always-open heading, and only a NESTED group as a collapsible
        // <details>. A section with a dozen flat pages is therefore a dozen permanent
        // sidebar rows. A nested group collapses — and auto-opens when the reader is
        // inside it — which is the only way to keep the sidebar navigable as sections
        // grow. See pim-docs/plans/user-documentation/content-structure.md.
        {
          label: 'Channels & feeds',
          items: [
            { slug: 'en/channels' },
            { slug: 'en/channels/setup-custom-product-feed' },
            {
              label: 'Template channels',
              collapsed: true,
              items: [
                { slug: 'en/channels/templates' },
                { slug: 'en/channels/templates/language' },
                { slug: 'en/channels/templates/data' },
                { slug: 'en/channels/templates/translations' },
                { slug: 'en/channels/templates/assets' },
                { slug: 'en/channels/templates/custom-entities' },
                { slug: 'en/channels/templates/functions' },
                { slug: 'en/channels/templates/testing' },
              ],
            },
          ],
        },
        { label: 'Brand portal', items: [{ autogenerate: { directory: 'en/brand-portal' } }] },
        { label: 'Account administration', items: [{ autogenerate: { directory: 'en/administration' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'en/reference' } }] },
        { label: 'Troubleshooting', items: [{ autogenerate: { directory: 'en/troubleshooting' } }] },
      ],
    }),
  ],
});
